### ISSUE TITLE
ERROR install degit

### ISSUE THREAD

**Issue by ahhzaky** [Rich-Harris/degit#287]
![image](https://user-images.githubusercontent.com/50357969/117480906-6a61ab00-af8c-11eb-8195-b96b3b4c155d.png)

**Comment by ahhzaky** [comment]
can anyone help me, why is my DEGIT like this?👋✋

**Comment by nake89** [comment]
There is a old PR about this: https://github.com/Rich-Harris/degit/pull/179
But it has not yet been merged.
Essentially the `--help` does not work. Otherwise the degit works fine (apart from gitlab).
This project isn't 100% actively maintained. If you want to checkout a fork that has that PR and others merged (gitlab functionality fixed):
https://github.com/tiged/tiged
Disclaimer: I am the maintainer of that repo.

**Comment by ahhzaky** [comment]
Thank you!👍👍
