### ISSUE TITLE
Docs/Actions(degit.json)

### ISSUE THREAD

**Issue by Pedroglp** [Rich-Harris/degit#36]
Hi,

First of all, thanks for the awesome tool.
But while reading the documentation there are no cues about where degit.json needs to be placed. 
For my surprise (reading the code), it needs to be set at the destination folder and not at src ('.').
This is a bit counter intuitive, since I don't have control of some repos I want to "clone" with degit and even if first create the destination folder with degit.json file it won't work it will be cleaned after the extraction.

My suggestion it is to add: --config 'path' to command line or set as default '.' location and also clarify it at the docs.

Cheers,

Pedro.

**Comment by ptone** [comment]
I'm confused about the use of actions as well, and rather than open a new issue, will just add some observations to this one.  If the dest folder is non-empty, degit errors out early.

If you use the documented example of License, and the cloned repo has such a file, degit will still complain that the file does not exist.

Stepping through the code a bit, and the exists check is performed before the file is copied, so I'm confused as to what the intended behavior is.

-P

**Comment by mhkeller** [comment]
Hi @Pedroglp , I [put in a PR](https://github.com/Rich-Harris/degit/pull/65) to fix some issues with actions but want to make sure I understand what you're running into. The degit.json file can go in your local folder that you're degit'ing into. For example,

```
degit rich-harris/degit-test-repo my-new-app
```

where the `my-new-app` can have a degit.json file in it. Definitely the docs need to be improved to clarify how its workflow and to provide some better examples.

@ptone, I think this is the same issue as https://github.com/Rich-Harris/degit/issues/38, which that PR should fix. Let me know if that fixes it for you, or you're seeing something else.

**Comment by mhkeller** [comment]
>  If the dest folder is non-empty, degit errors out early.

@ptone If you are creating a new local folder with a degit.json file in it, you would still need to use the `--force` flag since it's not empty. I'm not sure if it's a good idea to allow degit.json to be a privileged file that can exist without throwing an error. I was experimenting with [that here](https://github.com/Rich-Harris/degit/pull/65/commits/b7e522d5cfe62cfed3329a1ca4d22695d6ea4c8a) but open to ideas of what you think the expected behavior would be.
