### ISSUE TITLE
dest directory does not exists when executing actions

### ISSUE THREAD

**Issue by osdevisnot** [Rich-Harris/degit#38]
First and foremost, thank you so much for this awesome tool. Saves me so much time scaffolding new repos everyday.

While attempting to use the new actions feature, I wanted to have a `degit.json` in the same repository to be able to specify actions to be executed after clone.

For example, In this repo, https://github.com/osdevisnot/degit-demo -- I have a `degit.json` file as:
```json
[
  {
    "action": "remove",
    "files": ["README.md", "degit.json"]
  }
]
```

and I was expecting this will remove specific files when one clones this template with command like this:

```
degit osdevisnot/degit-demo my-app
```

However, this errors out with message:
```
! action wants to remove README.md but it does not exist
```

On further investigation, it seems when actions are specified, we are attempting to stash files before executing command in destination folder here:
https://github.com/Rich-Harris/degit/blob/master/src/index.js#L121

**This seems misleading, the actions are being executed in `dest` directory, which was stashed right before and does not exist when executing this command.**

What solution approach should I follow to achieve this use case?

**Comment by YogliB** [comment]
I assumed that the use case you describe is the one the action is intended for, am I wrong?

**Comment by osdevisnot** [comment]
That's absolutely correct. The action is intended for removing list of files.

**Comment by YogliB** [comment]
@mhkeller ?

**Comment by mhkeller** [comment]
Sorry for the delay on this and for the problem in the first place! The short answer is I wasn't accounting for running a `remove` action without a clone action first. So what was happening was:

1. You clone down your repo
2. You files are stashed because degit assumed the files in your repo were the final ones you wanted
3. It runs your remove command but things are stashed so nothing happens
4. Your files get unstashed and you get your original files

The use case I was designing for is

1. Same as above
2. Same as above
3. I figured you would have a clone command here to bring in some new files
4. You have a remove command here to get rid of files from step three
5. Your files get unstashed and you get your original files, overwriting any files currently in your directory from step 3 since degit assumes files that you began with are the ones you want to end with

This isn't how it should work though and you should be able to remove files locally first, [as I had said was possible](https://github.com/Rich-Harris/degit/pull/28#issuecomment-372541432).

This PR fixes the issue with more sensible stashing / unstashing and better explains the desired logic: https://github.com/Rich-Harris/degit/pull/65 Let me know what you think!
