### ISSUE TITLE
Question: How is that different from using "--depth 1"

### ISSUE THREAD

**Issue by KhaledElAnsari** [Rich-Harris/degit#7]
Hey, thank you for your work but I want to ask what is the difference between your project and using `git clone --depth 1` which will cause getting only the last commit

And for the branches I believe git has a solution for that too using `git clone -b <branch> <remote_repo>`

**Comment by Rich-Harris** [comment]
A few differences:

* If you `git clone`, you get a `.git` folder that pertains to the project template, rather than your project. You can easily forget to re-init the repository, and end up confusing yourself
* Caching (if you already have a `.tar.gz` file for a specific commit, you don't need to fetch it again)
* Less to type (`degit user/repo` instead of `git clone --depth 1 git@github.com:user/repo`)
* Future capabilities — [interactive mode](https://github.com/Rich-Harris/degit/issues/4), [friendly onboarding and postinstall scripts](https://github.com/Rich-Harris/degit/issues/6)

**Comment by Rich-Harris** [comment]
Oh, and a corollary to the caching thing — it could work offline, if we stored some extra metadata. Useful if you need to work on the train etc

**Comment by KhaledElAnsari** [comment]
Aha I see, thanks @Rich-Harris

**Comment by V-kremenlieva** [comment]
> A few differences:
> 
> * If you `git clone`, you get a `.git` folder that pertains to the project template, rather than your project. You can easily forget to re-init the repository, and end up confusing yourself
> * Caching (if you already have a `.tar.gz` file for a specific commit, you don't need to fetch it again)
> * Less to type (`degit user/repo` instead of `git clone --depth 1 git@github.com:user/repo`)
> * Future capabilities — [interactive mode](https://github.com/Rich-Harris/degit/issues/4), [friendly onboarding and postinstall scripts](https://github.com/Rich-Harris/degit/issues/6)
