### ISSUE TITLE
How to keep a scaffolding up to date?

### ISSUE THREAD

**Issue by msafi** [Rich-Harris/degit#9]
I'm looking for a tool to keep initial scaffolding up to date.

Like say some linting rules were part of an initial scaffolding. Then we updated the rules in the source repo. Now how do we bring the updated rules to the project that was scaffolded using our source repo?

This is something I'm really interested in and might be able to find time to work on it if you have some ideas?

**Comment by Rich-Harris** [comment]
To be honest I don't think there's a good general solution to that problem. Updating a file that you haven't changed might be straightforward enough, but if you'd added your own linting rules (for example) then it becomes much more complicated. And then there are things like files being renamed, etc. I think it's better to completely decouple the template from the project once it's been created, otherwise you're talking about a *lot* of engineering effort (which is against this project's philosophy) for minimal gain.

The nice thing about the repo-as-template model is that we already have a pretty good way of solving this problem: visit the repo and look at the commit history, either for the repo as a whole or the file that you're interested in such as `.eslintrc.json`. Then you can easily just copy and paste the new data into your project, manually addressing any deviations that would be almost impossible to automate. Or if your git-fu is strong, you could even pull specific commits from the template into your project.

I think that's better than building something complicated and degit-specific, so I'll close this issue. Thanks!
